//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyGuest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessagesInDiscussion> MessagesInDiscussions { get; set; }
        public virtual DbSet<Occasion> Occasions { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Traveling> Travelings { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<PlacePhotoView> PlacePhotoViews { get; set; }
        public virtual DbSet<UserGroupView> UserGroupViews { get; set; }
        public virtual DbSet<UserMessagerView> UserMessagerViews { get; set; }
        public virtual DbSet<UserOccasionView> UserOccasionViews { get; set; }
        public virtual DbSet<UserPhotoView> UserPhotoViews { get; set; }
        public virtual DbSet<UserPlaceView> UserPlaceViews { get; set; }
        public virtual DbSet<UserSityDiscussionView> UserSityDiscussionViews { get; set; }
        public virtual DbSet<UserSityTravelsView> UserSityTravelsViews { get; set; }
    }
}
