//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyGuest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Discussions = new HashSet<Discussion>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdUserCreate { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string Sity { get; set; }
    
        public virtual ICollection<Discussion> Discussions { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
