//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyGuest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.UserProfiles = new HashSet<UserProfile>();
            this.Places = new HashSet<Place>();
            this.UserProfiles1 = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<UserProfile> UserProfiles1 { get; set; }
    }
}
