//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyGuest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Photos = new HashSet<Photo>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public int IdUser { get; set; }
        public string Adress { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
