//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyGuest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOccasionView
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime CheckOut { get; set; }
        public string CommintHost { get; set; }
        public string CommintTreveler { get; set; }
        public string LoginTraveler { get; set; }
        public string loginHost { get; set; }
    }
}
