//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyGuest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessagerView
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataTimeRead { get; set; }
        public System.DateTime DataTimeWrite { get; set; }
        public string LoginUserWrite { get; set; }
        public string LoginUserRead { get; set; }
        public string Text { get; set; }
    }
}
