//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Discussions = new HashSet<Discussion>();
            this.Groups = new HashSet<Group>();
            this.Places = new HashSet<Place>();
            this.Travelings = new HashSet<Traveling>();
        }
    
        public int Id { get; set; }
        public int IdCountry { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Discussion> Discussions { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<Traveling> Travelings { get; set; }
    }
}
