//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Discussions = new HashSet<Discussion>();
            this.Photos = new HashSet<Photo>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IdUserCreate { get; set; }
        public string Description { get; set; }
        public System.DateTime DataTimeCreate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Discussion> Discussions { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
