//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occasion
    {
        public Occasion()
        {
            this.Travelings = new HashSet<Traveling>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Id { get; set; }
        public string IdUserTraveler { get; set; }
        public string IdUserHost { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime CheckOut { get; set; }
        public string CommintTreveler { get; set; }
        public string CommintHost { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<Traveling> Travelings { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
