//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public string IdUserCreate { get; set; }
        public Nullable<int> IdDiscussion { get; set; }
        public bool Main { get; set; }
        public System.DateTime DataTimeCreate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Discussion Discussion { get; set; }
        public virtual Group Group { get; set; }
        public virtual Place Place { get; set; }
        public virtual Traveling Traveling { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
