//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveling
    {
        public Traveling()
        {
            this.Occasions = new HashSet<Occasion>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateComing { get; set; }
        public System.DateTime DateDeparture { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string Sity { get; set; }
    
        public virtual ICollection<Occasion> Occasions { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
