//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPlace
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public int IdPlace { get; set; }
        public Nullable<System.DateTime> DataTimeComing { get; set; }
        public Nullable<System.DateTime> DateTimeDeparture { get; set; }
        public bool StatusComing { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Place Place { get; set; }
    }
}
